### ISSUE TITLE
what is the plan?

### ISSUE THREAD

**Issue by CyberneticDruid** [TBOT-Project/tbot-improvement-proposals#7]
As a contributor, I need some kind of goal or roadmap and to know what's already being worked on, in order to contribute effectively.

Or if you want random pull requests, that's less effective, but with more potential... maybe.

**Comment by CyberneticDruid** [comment]
I uploaded the TBOT writings image to IPFS and pinned it, to be censorship resistant, if that's helpful I can do a pull request

**Comment by tbothack** [comment]
> I uploaded the TBOT writings image to IPFS and pinned it, to be censorship resistant, if that's helpful I can do a pull request to add the CID and link to a gateway to some text file QmSc2CdqN64x957cab42opNzWhrrzhLnPehPZEJ8CbttZ6

Sounds good, thank you.

**Comment by tbothack** [comment]
> As a contributor, I need some kind of goal or roadmap and to know what's already being worked on, in order to contribute effectively.
> 
> Or if you want random pull requests, that's less effective, but with more potential... maybe.

We'll do kanban boards on Zenhub.
